version: "3.8"
services:
  lay-chat:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: lay-chat
    #image: lay-chat-app:latest
    #command: streamlit run main.py --server.port 8080 --server.address 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8080:8080
    networks:
      - lay-networks

  chroma-lay-db:
    container_name: chroma-lay-db
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - lay-networks

  postgres-lay:
    image: postgres:15-alpine
    container_name: postgres-lay
    restart: unless-stopped
    tty: true
    volumes:
      # - ./infra/postgres/data:/var/lib/postgresql/data #localpath
      - lay-db-data:/var/lib/postgresql/data
      - ./infra/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=homestead
    ports:
      - "5432:5432"
    networks:
      - lay-networks
    mem_limit: 6g

  pgadmin-lay:
    depends_on:
      - postgres-lay
    image: dpage/pgadmin4:latest
    ports:
      - "5480:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_DEFAULT_EMAIL=soporte.desarrollo@silent4business.com
    restart: unless-stopped
    tty: true
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - lay-networks

networks:
  lay-networks:
    driver: bridge

volumes:
  chroma-data:
    driver: local
  lay-db-data:
    driver: local
  pgadmin-data:
    driver: local
