FROM langchain/langchain

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade -r requirements.txt

COPY . /app

WORKDIR /app

# COPY bot.py .
# COPY utils.py .
# COPY chains.py .

EXPOSE 8080

HEALTHCHECK CMD curl --fail http://localhost:8080/_stcore/health
CMD ["streamlit", "run", "main.py", "--server.port=8080", "--server.address=0.0.0.0"]

# ENTRYPOINT ["streamlit", "run", "chatservice/main.py", "--server.port=8080", "--server.address=0.0.0.0"]